// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
// Firebase Web API initialization
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLoWw2NKa93cyvOVAoBxJO7sGc0EpOHlA',
    appId: '1:1000384075444:web:1644aac34173c262a5a9e1',
    messagingSenderId: '1000384075444',
    projectId: 'speed-scroll',
    authDomain: 'speed-scroll.firebaseapp.com',
    storageBucket: 'speed-scroll.appspot.com',
  );
// Firebase Android API initialization (use this one)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBm1XU1mOFMIcLz1HuHcPaskGlXcUkIs4',
    appId: '1:1000384075444:android:cade5597fe5b80e7a5a9e1',
    messagingSenderId: '1000384075444',
    projectId: 'speed-scroll',
    storageBucket: 'speed-scroll.appspot.com',
  );
// Firebase IOS API initialization
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZI__KlUCF7AqroDAVBuEES7itSCRacpk',
    appId: '1:1000384075444:ios:2d00e08ef9a81924a5a9e1',
    messagingSenderId: '1000384075444',
    projectId: 'speed-scroll',
    storageBucket: 'speed-scroll.appspot.com',
    iosBundleId: 'com.example.authUi',
  );
// Firebase MacOS API initialization
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZI__KlUCF7AqroDAVBuEES7itSCRacpk',
    appId: '1:1000384075444:ios:2d00e08ef9a81924a5a9e1',
    messagingSenderId: '1000384075444',
    projectId: 'speed-scroll',
    storageBucket: 'speed-scroll.appspot.com',
    iosBundleId: 'com.example.authUi',
  );
// Firebase Windows API initialization
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLoWw2NKa93cyvOVAoBxJO7sGc0EpOHlA',
    appId: '1:1000384075444:web:d0e0ff2a832f788ea5a9e1',
    messagingSenderId: '1000384075444',
    projectId: 'speed-scroll',
    authDomain: 'speed-scroll.firebaseapp.com',
    storageBucket: 'speed-scroll.appspot.com',
  );
}
